version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/flight_school.db
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - BASE_URL=${BASE_URL}
    depends_on:
      - mail

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/tmp
    volumes:
      - mail_data:/tmp

volumes:
  instance:
  mail_data: 
