"""update_schema

Revision ID: d3d9696d8106
Revises: a09e135fb12f
Create Date: 2025-03-29 06:17:50.216907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d9696d8106'
down_revision: Union[str, None] = 'a09e135fb12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('type', sa.String(), nullable=True))
    op.add_column('aircraft', sa.Column('model', sa.String(), nullable=True))
    op.drop_column('aircraft', 'make_model')
    op.add_column('flights', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('instructors', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('instructors', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('instructors', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('instructors', sa.Column('rating', sa.String(), nullable=True))
    op.add_column('instructors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('instructors', 'flight_reviews')
    op.drop_column('instructors', 'endorsements')
    op.drop_column('instructors', 'currency')
    op.drop_column('instructors', 'ratings')
    op.drop_column('instructors', 'full_name')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('instructors', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('ratings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('endorsements', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instructors', sa.Column('flight_reviews', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('instructors', 'is_active')
    op.drop_column('instructors', 'rating')
    op.drop_column('instructors', 'last_name')
    op.drop_column('instructors', 'first_name')
    op.drop_column('instructors', 'hashed_password')
    op.drop_column('flights', 'duration')
    op.add_column('aircraft', sa.Column('make_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('aircraft', 'model')
    op.drop_column('aircraft', 'type')
    # ### end Alembic commands ###
